### ISSUE TITLE
Ponle la propiedad fetch = FetchType.LAZY

### ISSUE THREAD

**Issue by Lainezz** [jujocave97/ProyectoStockControl#1]
https://github.com/jujocave97/ProyectoStockControl/blame/71734d095abb51441d7be83c6d88463cc1058d71/src/main/java/com/es/stockcontrol/model/Proveedor.java#L21

Ponle la propiedad fetch = FetchType.LAZY

¿Sabes esa propiedad qué hace?

**Comment by jujocave97** [comment]
si, sabemos que hace el fetch lazy, ya está cambiado
se nos habia pasado, gracias

**Comment by Lainezz** [comment]
Perfecto
