### ISSUE TITLE
Ponle la anotación @Temporal

### ISSUE THREAD

**Issue by Lainezz** [jujocave97/ProyectoStockControl#2]
https://github.com/jujocave97/ProyectoStockControl/blame/71734d095abb51441d7be83c6d88463cc1058d71/src/main/java/com/es/stockcontrol/model/Producto.java#L29

Ponle la anotación @Temporal

**Comment by jujocave97** [comment]
si, sabemos que hace el fetch lazy, ya está cambiado se nos habia pasado, gracias

**Comment by Jaregonz** [comment]
Listo, se ha añadido la anotación @Temporal a la propiedad fechaAlta
